[data]
x = "x"
y = "y"
z = "z"
gene = "feature_name"
min_molecules_per_gene = 10
exclude_genes = "NegControl*,BLANK_*,antisense_*,NegControlCodeword_*"
min_molecules_per_cell = 50

[segmentation]
unassigned_prior_label = "UNASSIGNED"
prior_segmentation_confidence = 0.5

[plotting]
min_pixels_per_cell = 10