from .plotting import (
    apply_exrnaH_to_cellular_to_create_cellularW,
    coupled_scatter,
    genes_over_noise,
    heatmap,
    interactions_with_arrows,
    moranI_histogram,
    nmf_factors_exrna_cells_W,
    nmf_gene_contributions,
    paired_nmf_factors,
    pie_of_positive,
    plot_crosstab,
    proportion_above_threshold,
    sorted_heatmap,
    spatial_interactions,
)
